Repository codestates-seb/seb43_main_017, pull requests merged in 2023-05, with the labels that each got.

#50 Feat : be-feat-JwtToken인증구현#39
  server/mainProject/build.gradle
  server/mainProject/src/main/java/com/codestates/mainProject/auth/WebConfig.java
  server/mainProject/src/main/java/com/codestates/mainProject/auth/config/PasswordEncoderConfig.java
  server/mainProject/src/main/java/com/codestates/mainProject/auth/config/SecurityConfiguration.java
  server/mainProject/src/main/java/com/codestates/mainProject/auth/dto/LoginDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/auth/dto/TokenPrincipalDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/auth/filter/JwtAuthenticationFilter.java
  server/mainProject/src/main/java/com/codestates/mainProject/auth/filter/JwtVerificationFilter.java
  server/mainProject/src/main/java/com/codestates/mainProject/auth/handler/MemberAccessDeniedHandler.java
  server/mainProject/src/main/java/com/codestates/mainProject/auth/handler/MemberAuthenticationEntryPoint.java
  server/mainProject/src/main/java/com/codestates/mainProject/auth/handler/MemberAuthenticationFailureHandler.java
  server/mainProject/src/main/java/com/codestates/mainProject/auth/handler/MemberAuthenticationSuccessHandler.java
  server/mainProject/src/main/java/com/codestates/mainProject/auth/handler/OAuth2MemberSuccessHandler.java
  server/mainProject/src/main/java/com/codestates/mainProject/auth/jwt/JwtTokenizer.java
  server/mainProject/src/main/java/com/codestates/mainProject/auth/userdetails/MemberDetailsService.java
  server/mainProject/src/main/java/com/codestates/mainProject/auth/utils/CustomAuthorityUtils.java
  server/mainProject/src/main/java/com/codestates/mainProject/auth/utils/ErrorResponder.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/controller/HelloHomeController.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/dto/MemberDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/entity/Member.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/mapper/MemberMapper.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/repository/MemberRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/service/OAuth2MemberService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/entity/PlayList.java
  server/mainProject/src/main/resources/application-local.yaml
  server/mainProject/src/main/resources/templates/hello-oauth2.html
  server/mainProject/src/main/resources/templates/index.html
Labels: BE

#53 feat : be-feat-playList#51
  server/mainProject/src/main/java/com/codestates/mainProject/playList/entity/PlayList.java
Labels: BE, Feat

#56 Feat : 컨트롤러,서비스구현#42#43
  server/mainProject/src/main/java/com/codestates/mainProject/auth/config/SecurityConfiguration.java
  server/mainProject/src/main/java/com/codestates/mainProject/auth/filter/JwtAuthenticationFilter.java
  server/mainProject/src/main/java/com/codestates/mainProject/auth/jwt/JwtTokenizer.java
  server/mainProject/src/main/java/com/codestates/mainProject/exception/ExceptionCode.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/dto/MemberDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/entity/Member.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/mapper/MemberMapper.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
  server/mainProject/src/main/resources/templates/index.html
Labels: BE, Feat

#64 Feat : Image파일등록,조회기능구현#57
  server/mainProject/src/main/java/com/codestates/mainProject/auth/WebConfig.java
  server/mainProject/src/main/java/com/codestates/mainProject/auth/config/SecurityConfiguration.java
  server/mainProject/src/main/java/com/codestates/mainProject/exception/ExceptionCode.java
  server/mainProject/src/main/java/com/codestates/mainProject/image/FileStorageProperties.java
  server/mainProject/src/main/java/com/codestates/mainProject/image/FileStorageService.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/dto/MemberDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/mapper/PlayListMapper.java
  server/mainProject/src/main/resources/application-local.yaml
Labels: BE, Feat

#68 be-feat-PlayListService#60
  server/mainProject/src/main/java/com/codestates/mainProject/playList/mapper/PlayListMapper.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
Labels: BE, Feat

#73 PlayListService#60 플레이리스트 서비스 구현
  server/mainProject/src/main/java/com/codestates/mainProject/playList/dto/PlayListDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/entity/PlayList.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/mapper/PlayListMapper.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
Labels: BE, Feat

#88 PlayList Controller 구현 (미완성)
  server/mainProject/src/main/java/com/codestates/mainProject/playList/controller/PlayListController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/dto/PlayListDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/entity/PlayList.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
Labels: BE, Feat

#90 Fix : PlayList오류 수정 및 권한추가#89
  server/mainProject/build.gradle
  server/mainProject/src/main/java/com/codestates/mainProject/audit/Auditable.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/controller/HelloHomeController.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/entity/Member.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/controller/PlayListController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/dto/PlayListDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/entity/PlayList.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/mapper/PlayListMapper.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/service/PlayListLikeService.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/dto/TokenPrincipalDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/filter/JwtAuthenticationFilter.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/filter/JwtVerificationFilter.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/handler/OAuth2MemberSuccessHandler.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/config/SecurityConfiguration.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/config/WebConfig.java
Labels: BE, Feat, Fix

#92 Fix : Auditable수정#91
  server/mainProject/src/main/java/com/codestates/mainProject/MainProjectApplication.java
  server/mainProject/src/main/java/com/codestates/mainProject/audit/Auditable.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/dto/MemberDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/dto/PlayListDto.java
Labels: BE, Fix

#96 Feat : Member 기능 변경 및 추가#95
  server/mainProject/src/main/java/com/codestates/mainProject/member/controller/HelloHomeController.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/entity/Member.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/repository/MemberRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/service/OAuth2MemberService.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/handler/OAuth2MemberSuccessHandler.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/config/SecurityConfiguration.java
  server/mainProject/src/main/resources/application-local.yaml
  server/mainProject/src/main/resources/templates/hello-oauth2.html
  server/mainProject/src/main/resources/templates/index.html
Labels: BE, Feat, Refactoring

#106 Feat : 네이버 oauth2 로그인 기능 구현#105
  server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/dto/AuthLoginDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/mapper/MemberMapper.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/attributes/OAuthAttributes.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/filter/JwtAuthenticationFilter.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/handler/OAuth2MemberSuccessHandler.java
  server/mainProject/src/main/resources/application-local.yaml
Labels: BE, Feat

#108 Feat : 네이버 oauth2 로그인 및 회원가입 기능 구현#107
  server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/repository/MemberRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
Labels: BE, Feat, Fix

#111 feat : be-feat-PlayListMusicAddDelete#104
  .idea/compiler.xml
  .idea/modules.xml
  .idea/modules/mainProject.main.iml
  server/mainProject/src/main/java/com/codestates/mainProject/playList/controller/PlayListController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/dto/PlayListDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/entity/PlayList.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
Labels: BE, Feat

#117 Feat : Oauth2 관련 코드 추가#116
  server/mainProject/build.gradle
  server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/dto/NaverUserInfo.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/handler/OAuth2MemberSuccessHandler.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/config/NaverOAuthConfig.java
Labels: BE, Feat, Fix

#121 addMusicToPlayList#120 플레이 리스트에 음악 추가 기능 수정
  server/mainProject/src/main/java/com/codestates/mainProject/playList/controller/PlayListController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
Labels: BE, Fix

#123 Fix : 전체적인리팩터링#122
  server/mainProject/build.gradle
  server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/handler/OAuth2MemberSuccessHandler.java
Labels: BE, Refactoring

#135 Feat : AWS관련.yml파일추가#134"
  server/mainProject/src/main/resources/application-server.yml
Labels: BE, Feat

#137 PlayList 기능 수정 (memberId, memberName 자동할당)#136
  server/mainProject/src/main/java/com/codestates/mainProject/playList/controller/PlayListController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/dto/PlayListDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/entity/PlayList.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/mapper/PlayListMapper.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/repository/PlayListRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/dto/PlayListLikeDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/entity/PlayListLike.java
  server/mainProject/src/main/resources/application-local.yaml
Labels: BE, Fix

#139 Refactor : Member 코드 리팩터링#138
  server/mainProject/src/main/java/com/codestates/mainProject/member/entity/Member.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/handler/OAuth2MemberSuccessHandler.java
  server/mainProject/src/main/resources/application-server.yml
Labels: BE, Refactoring

#141 PlayListLike 구현 #140
  server/mainProject/src/main/java/com/codestates/mainProject/exception/ExceptionCode.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/dto/PlayListDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/entity/PlayList.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/controller/PlayListLikeController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/dto/PlayListLikeDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/entity/PlayListLike.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/repository/PlayListLikeRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/service/PlayListLikeService.java
Labels: BE, Feat

#144 PlayListLike 수정중
  server/mainProject/src/main/java/com/codestates/mainProject/playList/entity/PlayList.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/controller/PlayListLikeController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/dto/PlayListLikeDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/entity/PlayListLike.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/mapper/PlayListLikeMapper.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/service/PlayListLikeService.java
Labels: BE, Fix

#145 feature/be-feat-PlayListLikeUpgrade#112
  .idea/compiler.xml
  .idea/modules.xml
  .idea/modules/com.codestates.mainProject.main.iml
  server/mainProject/src/main/java/com/codestates/mainProject/playList/controller/PlayListController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/dto/PlayListDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/entity/PlayList.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/controller/PlayListLikeApiController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/controller/PlayListLikeController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/dto/PlayListLikeDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/entity/PlayListLike.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/mapper/PlayListLikeMapper.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/repository/PlayListLikeRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/service/PlayListLikeService.java
Labels: BE, Feat

#148 Feat : LocalDateTime 서울/아시아로 고정기능 추가 #147
  server/mainProject/src/main/java/com/codestates/mainProject/audit/LocaleConfig.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/oAuth2User/NaverOAuth2User.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/oAuth2User/NaverOAuth2UserRequest.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/userdetails/NaverOAuth2UserService.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/config/SecurityConfiguration.java
Labels: BE, Feat

#149 Fix : 기타
  server/mainProject/src/main/java/com/codestates/mainProject/security/config/SecurityConfiguration.java
Labels: BE, Fix

#152 playList entity (create -> createMember)
  server/mainProject/src/main/java/com/codestates/mainProject/playList/entity/PlayList.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
Labels: BE, Fix

#153 feature/PlayListComment#142
  server/mainProject/src/main/java/com/codestates/mainProject/playList/dto/PlayListDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListComment/controller/CommentController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListComment/entity/PlayListComment.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListComment/repository/CommentRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListComment/service/CommentService.java
Labels: BE, Feat

#157 playlistLike -> playlist <- playlistComment 연결 및 DB 데이터 삽입 #154
  server/mainProject/src/main/java/com/codestates/mainProject/playList/controller/PlayListController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/dto/PlayListDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/entity/PlayList.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListComment/controller/CommentController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListComment/repository/CommentRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListComment/service/CommentService.java
Labels: BE, Fix

#164 Refactor : Member 리팩터링#163
  server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/dto/MemberDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/mapper/MemberMapper.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/repository/MemberRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/entity/PlayList.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/handler/OAuth2MemberSuccessHandler.java
Labels: BE, Refactoring

#169 Feat : AWS S3에 프로필이미지 저장기능구현 및 oauth2 로그인 필드값 추가#165
  server/mainProject/build.gradle
  server/mainProject/src/main/java/com/codestates/mainProject/image/AwsS3Config.java
  server/mainProject/src/main/java/com/codestates/mainProject/image/FileStorageProperties.java
  server/mainProject/src/main/java/com/codestates/mainProject/image/FileStorageService.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/dto/AuthLoginDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/entity/Member.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/mapper/MemberMapper.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
  server/mainProject/src/main/resources/application-local.yaml
  server/mainProject/src/main/resources/application-server.yml
Labels: BE, Feat

#178 Fix:dev-fix-MusicLike기능수정#177
  server/mainProject/src/main/java/com/codestates/mainProject/exception/ExceptionCode.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicComment/controller/MusicCommentController.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicComment/service/MusicCommentService.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicLike/controller/MusicLikeController.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicLike/dto/MusicLikeDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicLike/mapper/MusicLikeMapper.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicLike/service/MusicLikeService.java
Labels: BE, Fix

#181 Fix:dev-fix-MusicController수정#180
  server/mainProject/src/main/java/com/codestates/mainProject/music/controller/MusicController.java
  server/mainProject/src/main/java/com/codestates/mainProject/music/service/MusicService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
Labels: BE, Fix

#182 feature/PlayList-Data-Connection#154 (playlist, comment, like 작업)
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/modules.xml
  server/mainProject/src/main/java/com/codestates/mainProject/playList/controller/PlayListController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/dto/PlayListDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/entity/PlayList.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListComment/controller/CommentController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListComment/dto/CommentDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListComment/mapper/CommentMapper.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListComment/service/CommentService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/controller/PlayListLikeApiController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/controller/PlayListLikeController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/dto/LikeDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/entity/PlayListLike.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/mapper/PlayListLikeMapper.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/repository/PlayListLikeRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/service/PlayListLikeService.java
Labels: BE, Feat, Fix

#191 Fix:dev-fix-patchMusic메서드수정#190
  server/mainProject/src/main/java/com/codestates/mainProject/exception/ExceptionCode.java
  server/mainProject/src/main/java/com/codestates/mainProject/music/controller/MusicController.java
  server/mainProject/src/main/java/com/codestates/mainProject/music/dto/MusicDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/music/repository/MusicRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/music/service/MusicService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
Labels: BE, Fix

#195 Feat:dev-feat-키워드검색구현#192
  server/mainProject/src/main/java/com/codestates/mainProject/music/controller/MusicController.java
  server/mainProject/src/main/java/com/codestates/mainProject/music/repository/MusicRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/music/service/MusicService.java
Labels: BE, Feat

#198 Feat : MemberMusic, PlayListMusic 엔티티추가#189
  server/mainProject/src/main/java/com/codestates/mainProject/exception/ExceptionCode.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/entity/Member.java
  server/mainProject/src/main/java/com/codestates/mainProject/memberMusic/entity/MemberMusic.java
  server/mainProject/src/main/java/com/codestates/mainProject/memberMusic/repository/MemberMusicRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/memberMusic/service/MemberMusicService.java
  server/mainProject/src/main/java/com/codestates/mainProject/music/controller/MusicController.java
  server/mainProject/src/main/java/com/codestates/mainProject/music/dto/MusicDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/music/entity/Music.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/entity/PlayList.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playlListMusic/entity/PlayListMusic.java
  server/mainProject/src/main/java/com/codestates/mainProject/playlListMusic/repository/PlayListMusicRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/playlListMusic/service/PlayListMusicService.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/filter/JwtAuthenticationFilter.java
Labels: BE, Feat

#200 fix/be-fix-Add-PlayList-music#186 (음악 추가, 커버 이미지, 태그)
  .idea/.name
  server/mainProject/.gitignore
  server/mainProject/src/main/generated/com/codestates/mainProject/member/mapper/MemberMapperImpl.java
  server/mainProject/src/main/generated/com/codestates/mainProject/music/mapper/MusicMapperImpl.java
  server/mainProject/src/main/generated/com/codestates/mainProject/playList/mapper/PlayListMapperImpl.java
  server/mainProject/src/main/generated/com/codestates/mainProject/playListComment/mapper/CommentMapperImpl.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/dto/PlayListDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/entity/PlayList.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/controller/PlayListLikeController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/service/PlayListLikeService.java
Labels: BE, Fix

#201 Feat : FilterChain 권한관련 추가#199
  server/mainProject/.idea/.gitignore
  server/mainProject/.idea/aws.xml
  server/mainProject/.idea/gradle.xml
  server/mainProject/.idea/jarRepositories.xml
  server/mainProject/src/main/java/com/codestates/mainProject/security/config/SecurityConfiguration.java
Labels: BE, Feat

#204 be-feat-tags#183 태그 구현
  server/mainProject/src/main/java/com/codestates/mainProject/exception/ExceptionCode.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListComment/service/CommentService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/service/PlayListLikeService.java
  server/mainProject/src/main/java/com/codestates/mainProject/tags/controller/TagController.java
  server/mainProject/src/main/java/com/codestates/mainProject/tags/dto/TagDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/tags/entity/Tag.java
  server/mainProject/src/main/java/com/codestates/mainProject/tags/repository/TagRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/tags/service/TagService.java
Labels: BE, Feat, Fix

#209 Feat : MusicTag 구현 #208
  server/mainProject/src/main/java/com/codestates/mainProject/exception/ExceptionCode.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
  server/mainProject/src/main/java/com/codestates/mainProject/memberMusic/service/MemberMusicService.java
  server/mainProject/src/main/java/com/codestates/mainProject/music/controller/MusicController.java
  server/mainProject/src/main/java/com/codestates/mainProject/music/entity/Music.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicLike/service/MusicLikeService.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicTag/controller/MusicTagController.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicTag/dto/MusicTagDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicTag/entity/MusicTag.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicTag/repository/MusicTagRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicTag/service/MusicTagService.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/config/SecurityConfiguration.java
Labels: BE, Feat

#212 feature/be-feat-PlayList-Tag#205
  server/mainProject/src/main/java/com/codestates/mainProject/exception/ExceptionCode.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/controller/PlayListController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/dto/PlayListDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/entity/PlayList.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/repository/PlayListRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListComment/service/CommentService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/service/PlayListLikeService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListTag/controller/PlayListTagController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListTag/dto/PlayListTagDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListTag/entity/PlayListTag.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListTag/repository/PlayListTagRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListTag/service/PlayListTagService.java
Labels: BE, Feat, Fix

#224 Feat : PlaylistLike 연관관계매핑기타
  server/mainProject/src/main/java/com/codestates/mainProject/member/entity/Member.java
Labels: BE, Feat

#226 be-fix-memberPlaylist#220
  server/mainProject/src/main/java/com/codestates/mainProject/member/entity/Member.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/controller/PlayListController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/repository/PlayListLikeRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/service/PlayListLikeService.java
Labels: BE, Fix

#236 Feat : 뮤직 추천 기능 구현 #235
  server/mainProject/build.gradle
  server/mainProject/src/main/java/com/codestates/mainProject/exception/ExceptionCode.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/entity/Member.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
  server/mainProject/src/main/java/com/codestates/mainProject/memberMusicTag/entity/MemberMusicTag.java
  server/mainProject/src/main/java/com/codestates/mainProject/memberMusicTag/repository/MemberMusicTagRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/memberMusicTag/service/MemberMusicTagService.java
  server/mainProject/src/main/java/com/codestates/mainProject/music/repository/MusicRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicLike/service/MusicLikeService.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicTag/repository/MusicTagRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/filter/JwtVerificationFilter.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/config/SecurityConfiguration.java
Labels: BE, Feat

#238 Feat : 태그에 카테고리 추가 및 태그리팩터링 #237
  server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
  server/mainProject/src/main/java/com/codestates/mainProject/tags/controller/TagController.java
  server/mainProject/src/main/java/com/codestates/mainProject/tags/dto/TagDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/tags/entity/Tag.java
  server/mainProject/src/main/java/com/codestates/mainProject/tags/repository/TagRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/tags/service/TagService.java
Labels: BE, Feat

#245 Feat:dev-feat-Tag검색기능구현#193
  server/mainProject/src/main/java/com/codestates/mainProject/music/dto/MusicDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/music/repository/MusicRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicLike/dto/MusicLikeDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/search/controller/SearchController.java
  server/mainProject/src/main/java/com/codestates/mainProject/search/service/SearchService.java
Labels: BE, Feat

#253 be-fix-playlist-refactoring#234
  .idea/compiler.xml
  .idea/modules.xml
  server/mainProject/src/main/java/com/codestates/mainProject/playList/controller/PlayListController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/dto/PlayListDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/controller/PlayListLikeController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/repository/PlayListLikeRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/service/PlayListLikeService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListTag/controller/PlayListTagController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListTag/dto/PlayListTagDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListTag/entity/PlayListTag.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListTag/repository/PlayListTagRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListTag/service/PlayListTagService.java
Labels: BE, Fix

#255 Feat:dev-feat-playList검색구현#254
  server/mainProject/src/main/java/com/codestates/mainProject/musicComment/dto/MusicCommentDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicComment/mapper/MusicCommentMapper.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/dto/PlayListDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/repository/PlayListRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/search/controller/SearchController.java
  server/mainProject/src/main/java/com/codestates/mainProject/search/service/SearchService.java
Labels: BE, Feat

#257 be-fix-playlist-refactoring#234
  server/mainProject/src/main/java/com/codestates/mainProject/playList/controller/PlayListController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/controller/PlayListLikeController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/service/PlayListLikeService.java
Labels: BE, Fix

#260 playlistlike @Table 어노테이션 삭제
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/entity/PlayListLike.java
Labels: BE, Fix

#262 멤버가 좋아요한 플레이리스트 조회기능 추가
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/controller/PlayListLikeController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/repository/PlayListLikeRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/service/PlayListLikeService.java
Labels: BE, Feat

#271 Feat : playlistTtag관련 보안설정#270
  server/mainProject/src/main/java/com/codestates/mainProject/security/config/SecurityConfiguration.java
  server/mainProject/src/main/resources/application-local.yaml
Labels: BE, Feat

#273 playlist tag 권한문제 해결 등..
  server/mainProject/src/main/java/com/codestates/mainProject/playListComment/controller/CommentController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListComment/dto/CommentDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListComment/entity/PlayListComment.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListComment/service/CommentService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/controller/PlayListLikeController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListTag/controller/PlayListTagController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListTag/service/PlayListTagService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playlListMusic/repository/PlayListMusicRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/playlListMusic/service/PlayListMusicService.java
  server/mainProject/src/main/java/com/codestates/mainProject/tags/controller/TagController.java
  server/mainProject/src/main/java/com/codestates/mainProject/tags/dto/TagDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/tags/entity/Tag.java
  server/mainProject/src/main/java/com/codestates/mainProject/tags/service/TagService.java
Labels: BE, Feat, Fix

#277 Feat : Music응답에 태그이름 추가 및 기타수정#276
  server/mainProject/src/main/java/com/codestates/mainProject/music/controller/MusicController.java
  server/mainProject/src/main/java/com/codestates/mainProject/music/dto/MusicDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/music/entity/Music.java
  server/mainProject/src/main/java/com/codestates/mainProject/music/service/MusicService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/entity/PlayList.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
  server/mainProject/src/main/java/com/codestates/mainProject/tags/entity/Tag.java
  server/mainProject/src/main/resources/application-server.yml
Labels: BE

#281 Fix:Search에 pagination 수정
  server/mainProject/src/main/java/com/codestates/mainProject/music/repository/MusicRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicLike/controller/MusicLikeController.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicLike/dto/MusicLikeDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicLike/service/MusicLikeService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/repository/PlayListRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/search/controller/SearchController.java
  server/mainProject/src/main/java/com/codestates/mainProject/search/service/SearchService.java
  server/mainProject/src/main/java/com/codestates/mainProject/utils/PageConverter.java
Labels: BE, Fix

#283 [fix] findAdminsPlayLists 수정
  server/mainProject/src/main/java/com/codestates/mainProject/playList/controller/PlayListController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/controller/PlayListLikeController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/service/PlayListLikeService.java
Labels: BE, Fix

#286 Fix : PlaylistLike 기타 수정 #285
  server/mainProject/.idea/aws.xml
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/controller/PlayListLikeController.java
  server/mainProject/src/main/java/com/codestates/mainProject/playListLike/service/PlayListLikeService.java
Labels: BE, Fix

#287 Feat : PlaylistComments 연관관계매핑
  server/mainProject/src/main/java/com/codestates/mainProject/playList/entity/PlayList.java
Labels: BE, Fix

#292 Fix:Search 카테고리에 페이지네이션 수정
  server/mainProject/src/main/java/com/codestates/mainProject/music/controller/MusicController.java
  server/mainProject/src/main/java/com/codestates/mainProject/music/service/MusicService.java
  server/mainProject/src/main/java/com/codestates/mainProject/search/controller/SearchController.java
Labels: BE, Fix

#294 Fix : 음악추천기능 중복노래 안 들어가게 수정 #293
  server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicLike/service/MusicLikeService.java
Labels: BE, Fix

#295 [fix] playlistDto Post (coverImg 삭제)
  server/mainProject/src/main/java/com/codestates/mainProject/playList/dto/PlayListDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/playList/service/PlayListService.java
Labels: BE, Fix

#296 Fix : musicService 부분 사라진 거 다시 추가
  server/mainProject/src/main/java/com/codestates/mainProject/musicLike/service/MusicLikeService.java
Labels: BE, Fix

#298 Fix : playlistPostDto 에 coverImg 필드 추가
  server/mainProject/src/main/java/com/codestates/mainProject/playList/dto/PlayListDto.java
Labels: BE, Fix

#305 Refactor : memeber관련 전체적인 리팩터링#304
  server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/dto/MemberDto.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/dto/NaverUserInfo.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/entity/Member.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
  server/mainProject/src/main/java/com/codestates/mainProject/memberMusic/entity/MemberMusic.java
  server/mainProject/src/main/java/com/codestates/mainProject/memberMusic/service/MemberMusicService.java
  server/mainProject/src/main/java/com/codestates/mainProject/memberMusicTag/entity/MemberMusicTag.java
  server/mainProject/src/main/java/com/codestates/mainProject/memberMusicTag/repository/MemberMusicTagRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/memberMusicTag/service/MemberMusicTagService.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicLike/service/MusicLikeService.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicTag/controller/MusicTagController.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicTag/entity/MusicTag.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicTag/repository/MusicTagRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicTag/service/MusicTagService.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/attributes/OAuthAttributes.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/filter/JwtAuthenticationFilter.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/handler/MemberAuthenticationFailureHandler.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/handler/OAuth2MemberSuccessHandler.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/jwt/JwtTokenizer.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/oAuth2User/NaverOAuth2User.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/oAuth2User/NaverOAuth2UserRequest.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/userdetails/NaverOAuth2UserService.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/utils/CustomAuthorityUtils.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/config/NaverOAuthConfig.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/config/SecurityConfiguration.java
Labels: BE, Refactoring

#307 Refactor:Music 카테고리 리팩토링#306
  server/mainProject/.idea/aws.xml
  server/mainProject/src/main/java/com/codestates/mainProject/music/mapper/MusicMapper.java
  server/mainProject/src/main/java/com/codestates/mainProject/music/repository/MusicRepository.java
  server/mainProject/src/main/java/com/codestates/mainProject/musicLike/mapper/MusicLikeMapper.java
Labels: BE, Refactoring

#308 [fix] 멤버 플레이리스트 조회 페이지 5 -> 3
  server/mainProject/src/main/java/com/codestates/mainProject/playList/controller/PlayListController.java
Labels: BE, Fix

#313 Fix:musicController기능수정#312
  server/mainProject/src/main/java/com/codestates/mainProject/music/controller/MusicController.java
  server/mainProject/src/main/java/com/codestates/mainProject/music/service/MusicService.java
Labels: BE, Fix

#326 Feat : 로컬 및 각 oAuth2 이메일 구분기능구현 #324
  server/mainProject/.idea/aws.xml
  server/mainProject/src/main/java/com/codestates/mainProject/member/controller/MemberContorller.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/entity/Member.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/handler/OAuth2MemberSuccessHandler.java
Labels: BE, Feat

#344 [fix] 플레이리스트 Patch 수정
  server/mainProject/src/main/java/com/codestates/mainProject/playList/dto/PlayListDto.java
Labels: BE, Fix

#351 Fix : 엑세스 토큰 시간 변경
  server/mainProject/src/main/resources/application-server.yml
Labels: BE, Fix

#369 Feat : Refresh 토큰 관련 코드 추가#367
  server/mainProject/src/main/java/com/codestates/mainProject/exception/ExceptionCode.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/entity/Member.java
  server/mainProject/src/main/java/com/codestates/mainProject/member/service/MemberService.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/controller/TokenController.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/filter/JwtVerificationFilter.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/handler/OAuth2MemberSuccessHandler.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/jwt/JwtTokenizer.java
  server/mainProject/src/main/java/com/codestates/mainProject/security/auth/service/TokenService.java
  server/mainProject/src/main/resources/application-local.yaml
  server/mainProject/src/main/resources/application-server.yml
Labels: BE, Feat
